server:
  port: 8092
spring:
  application:
    name: ms-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8091
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 #设置Sleuth的抽样收集概率    
eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://admin:Eccom123@localhost:8761/eureka/