server:
  port: 8761
spring:
  application:
    name: ek-center
  security:
    user:
      name: admin
      password: Eccom123
eureka:
  instance:
    hostname: ek-center
    appname: 注册中心
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false