server:
  port: 8761
eureka:
  instance:
    hostname: ek-center
    appname: 注册中心
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false