server:
  port: 8080
spring:
  application:
    name: ms-gateway
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 #设置Sleuth的抽样收集概率    
  cloud:
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gt-provider
          uri: lb://service-provider
          order: 8881
          predicates: 
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: gt-invoker
          uri: lb://service-invoker
          order: 8882
          predicates: 
            - Path=/invoker/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://admin:Eccom123@localhost:8761/eureka/