server:
  port: 8881
spring:
  application:
    name: service-provider
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 #设置Sleuth的抽样收集概率    
eureka:
  instance:
    hostname: localhost
    appname: service-provider
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://admin:Eccom123@localhost:8761/eureka/
