server:
  port: 8881
spring:
  application:
    name: service-provider
eureka:
  instance:
    hostname: localhost
    appname: service-provider
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://admin:Eccom123@localhost:8761/eureka/
