server:
  port: 8882
spring:
  application:
    name: service-invoker
eureka:
  instance:
    hostname: localhost
    appname: service-invoker
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
