server:
  port: 8091
spring:
  application:
    name: ms-admin-server
#  security: # 配置登录用户名和密码
#    user:
#      name: admin
#      password: Eccom123
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 #设置Sleuth的抽样收集概率    
eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://admin:Eccom123@localhost:8761/eureka/