server:
  port: 8096
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID
spring:
  application:
    name: ms-oauth2-jwt-client
oauth2-server-url: http://localhost:8095
eureka:
  instance:
    hostname: localhost
    appname: ms-oauth2-jwt-client
  client:
    service-url:
      defaultZone: http://admin:Eccom123@localhost:8761/eureka/
security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin123456
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key